# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 大帅归来
email: wangjizhu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The world has kissed my soul with its pain, asking for its return in songs.
  世界以痛吻我，我要报之以歌。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wangjizhu.github.io" # the base hostname & protocol for your site
# twitter_username: N/A
github_username:  wangjizhu
twitter_username:  dashuaiguilai

# Build settings
markdown: kramdown
